
import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    appName: "Gram Kalyan",
    tagline: "Government Scheme Information",
    welcomeTitle: "Welcome to Gram Kalyan",
    welcomeDesc: "Discover government schemes specially made for you and your family. Answer a few simple questions, and we will show you exactly what benefits you can get.",
    findSchemes: "Find My Schemes",
    easyToUse: "Easy to Use",
    easyToUseDesc: "No complex forms. Just simple questions.",
    aiPowered: "AI Powered",
    aiPoweredDesc: "Smart matching with current government data.",
    trustedInfo: "Trusted Info",
    trustedInfoDesc: "Direct links to official portals.",
    loginTitle: "Login to Portal",
    mobileLabel: "Mobile Number",
    mobilePlaceholder: "Enter 10 digit number",
    loginBtn: "Login",
    ageLabel: "How old are you?",
    genderLabel: "What is your gender?",
    male: "Male",
    female: "Female",
    other: "Other",
    incomeLabel: "Yearly Family Income (₹)",
    incomeDesc: "Include income of all family members.",
    occLabel: "What is your main work?",
    stateLabel: "Which State do you live in?",
    catLabel: "Social Category",
    next: "Next",
    back: "Back",
    showSchemes: "Show My Schemes",
    resultsTitle: "Schemes Found For You",
    changeDetails: "Change Details",
    quickSummary: "Quick Summary",
    viewBenefits: "View Benefits",
    whatIsThis: "What is this scheme?",
    listen: "Listen",
    stopListen: "Stop Listening",
    keyBenefits: "Key Benefits:",
    whoCanApply: "Who can apply?",
    howToApply: "How to apply?",
    officialPortal: "Go to Official Portal",
    loadingTitle: "Finding Best Schemes...",
    loadingDesc: "Checking details against latest criteria. Please wait.",
    errorTitle: "Something went wrong",
    tryAgain: "Try Again",
    footerText: "To help every villager access their rights.",
    footerDisclaimer: "Not an official government entity.",
    selectOcc: "Select Occupation",
    selectState: "Select State"
  },
  hi: {
    appName: "ग्राम कल्याण",
    tagline: "सरकारी योजना की जानकारी",
    welcomeTitle: "ग्राम कल्याण में आपका स्वागत है",
    welcomeDesc: "अपने और अपने परिवार के लिए विशेष रूप से बनाई गई सरकारी योजनाओं की खोज करें। कुछ सरल प्रश्नों के उत्तर दें, और हम आपको दिखाएंगे कि आपको क्या लाभ मिल सकते हैं।",
    findSchemes: "मेरी योजनाएं खोजें",
    easyToUse: "उपयोग में आसान",
    easyToUseDesc: "कोई जटिल फॉर्म नहीं। बस सरल प्रश्न।",
    aiPowered: "AI द्वारा संचालित",
    aiPoweredDesc: "नवीनतम सरकारी डेटा के साथ स्मार्ट मिलान।",
    trustedInfo: "विश्वसनीय जानकारी",
    trustedInfoDesc: "आधिकारिक पोर्टल के लिए सीधी लिंक।",
    loginTitle: "पोर्टल में लॉगिन करें",
    mobileLabel: "मोबाइल नंबर",
    mobilePlaceholder: "10 अंकों का नंबर दर्ज करें",
    loginBtn: "लॉगिन करें",
    ageLabel: "आपકી उम्र क्या है?",
    genderLabel: "आपका लिंग क्या है?",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    incomeLabel: "वार्षिक पारिवारिक आय (₹)",
    incomeDesc: "परिवार के सभी सदस्यों की आय शामिल करें।",
    occLabel: "आपका मुख्य कार्य क्या है?",
    stateLabel: "आप किस राज्य में रहते हैं?",
    catLabel: "सामाजिक श्रेणी",
    next: "आगे बढ़ें",
    back: "पीछे जाएं",
    showSchemes: "मेरी योजनाएं दिखाएं",
    resultsTitle: "आपके लिए योजनाएं",
    changeDetails: "विवरण बदलें",
    quickSummary: "त्वरित सारांश",
    viewBenefits: "लाभ देखें",
    whatIsThis: "यह योजना क्या है?",
    listen: "जानकारी सुनें",
    stopListen: "सुनना बंद करें",
    keyBenefits: "मुख्य लाभ:",
    whoCanApply: "कौन आवेदन कर सकता है?",
    howToApply: "आवेदन कैसे करें?",
    officialPortal: "आधिकारिक पोर्टल पर जाएं",
    loadingTitle: "सर्वश्रेष्ठ योजनाएं खोज रहे हैं...",
    loadingDesc: "विवरण की जांच कर रहे हैं। कृपया प्रतीक्षा करें।",
    errorTitle: "कुछ गलत हो गया",
    tryAgain: "पुनः प्रयास करें",
    footerText: "हर ग्रामीण को उनके अधिकार दिलाने में मदद करने के लिए।",
    footerDisclaimer: "यह कोई आधिकारिक सरकारी संस्था नहीं है।",
    selectOcc: "व्यवसाय चुनें",
    selectState: "राज्य चुनें"
  },
  gu: {
    appName: "ગ્રામ કલ્યાણ",
    tagline: "સરકારી યોજનાની જાણકારી",
    welcomeTitle: "ગ્રામ કલ્યાણમાં આપનું સ્વાગત છે",
    welcomeDesc: "તમારા અને તમારા પરિવાર માટે ખાસ બનાવેલી સરકારી યોજનાઓ શોધો. થોડા સરળ પ્રશ્નોના જવાબ આપો, અને અમે તમને બતાવીશું કે તમને કયા ફાયદા મળી શકે છે.",
    findSchemes: "મારી યોજનાઓ શોધો",
    easyToUse: "વાપરવામાં સરળ",
    easyToUseDesc: "કોઈ જટિલ ફોર્મ નથી. માત્ર સાદા પ્રશ્નો.",
    aiPowered: "AI દ્વારા સંચાલિત",
    aiPoweredDesc: "નવીનતમ સરકારી ડેટા સાથે સ્માર્ટ મેચિંગ.",
    trustedInfo: "વિશ્વાસપાત્ર માહિતી",
    trustedInfoDesc: "સત્તાવાર અરજી પોર્ટલની સીધી લિંક્સ.",
    loginTitle: "પોર્ટલમાં લોગિન કરો",
    mobileLabel: "મોબાઇલ નંબર",
    mobilePlaceholder: "10 અંકનો નંબર લખો",
    loginBtn: "લોગિન કરો",
    ageLabel: "તમારી ઉંમર કેટલી છે?",
    genderLabel: "તમારી જાતિ શું છે?",
    male: "પુરુષ",
    female: "સ્ત્રી",
    other: "અન્ય",
    incomeLabel: "વાર્ષિક કૌટુંબિક આવક (₹)",
    incomeDesc: "બધા સભ્યોની કુલ આવક લખો.",
    occLabel: "તમારો મુખ્ય વ્યવસાય શું છે?",
    stateLabel: "તમે કયા રાજ્યમાં રહો છો?",
    catLabel: "સામાજિક શ્રેણી",
    next: "આગળ વધો",
    back: "પાછા જાઓ",
    showSchemes: "યોજનાઓ બતાવો",
    resultsTitle: "તમારા માટે ખાસ યોજનાઓ",
    changeDetails: "વિગતો બદલો",
    quickSummary: "ટૂંકમાં માહિતી",
    viewBenefits: "ફાયદા જુઓ",
    whatIsThis: "આ યોજના શું છે?",
    listen: "માહિતી સાંભળો",
    stopListen: "સાંભળવાનું બંધ કરો",
    keyBenefits: "મુખ્ય લાભો:",
    whoCanApply: "કોણ અરજી કરી શકે?",
    howToApply: "અરજી કેવી રીતે કરવી?",
    officialPortal: "સત્તાવાર વેબસાઇટ પર જાઓ",
    loadingTitle: "યોજનાઓ શોધી રહ્યા છીએ...",
    loadingDesc: "અમે તમારી વિગતોની તપાસ કરી રહ્યા છીએ. રાહ જુઓ.",
    errorTitle: "કંઈક ભૂલ થઈ છે",
    tryAgain: "ફરી પ્રયાસ કરો",
    footerText: "દરેક ગ્રામજનને તેમના અધિકારો મેળવવામાં મદદ કરવા માટે.",
    footerDisclaimer: "આ કોઈ સત્તાવાર સરકારી સંસ્થા નથી.",
    selectOcc: "વ્યવસાય પસંદ કરો",
    selectState: "રાજ્ય પસંદ કરો"
  }
};

export const STATES: Record<Language, string[]> = {
  en: ["Andhra Pradesh", "Gujarat", "Maharashtra", "Rajasthan", "Uttar Pradesh", "Bihar", "Madhya Pradesh", "Karnataka", "Tamil Nadu", "West Bengal", "Punjab", "Haryana", "Delhi"],
  hi: ["आंध्र प्रदेश", "गुजरात", "महाराष्ट्र", "राजस्थान", "उत्तर प्रदेश", "बिहार", "मध्य प्रदेश", "कर्नाटक", "तमिलनाडु", "पश्चिम बंगाल", "पंजाब", "हरियाणा", "दिल्ली"],
  gu: ["આંધ્ર પ્રદેશ", "ગુજરાત", "મહારાષ્ટ્ર", "રાજસ્થાન", "ઉત્તર પ્રદેશ", "બિહાર", "મધ્ય પ્રદેશ", "કર્ણાટક", "તમિલનાડુ", "પશ્ચિમ બંગાળ", "પંજાબ", "હરિયાણા", "દિલ્હી"]
};

export const CATEGORIES: Record<Language, string[]> = {
  en: ["General", "OBC", "SC", "ST", "Minority"],
  hi: ["सामान्य", "OBC", "SC", "ST", "लघुमती"],
  gu: ["સામાન્ય", "OBC", "SC", "ST", "લઘુમતી"]
};

export const OCCUPATIONS: Record<Language, string[]> = {
  en: ["Farmer", "Laborer", "Artisan", "Business", "Student", "Unemployed", "Homemaker"],
  hi: ["ખેડૂત", "मजदूर", "કારીગર", "વ્યવસાય", "छात्र", "બેરોજગાર", "ગૃહિણી"],
  gu: ["ખેડૂત", "ખેતમજૂર", "કારીગર", "નાનો વ્યવસાય", "વિદ્યાર્થી", "બેરોજગાર", "ગૃહિણી"]
};
